version: "2"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./alert.rules:/etc/prometheus/alert.rules
      - ./prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    network_mode: host
    
 # grafana:
 #   image: grafana/grafana:latest
 #   volumes:
 #     - grafana_data:/var/lib/grafana
 #   environment:
 #     - GF_SECURITY_ADMIN_PASSWORD=admin
 #   depends_on:
 #     - prometheus
 #   ports:
 #     - "3000:3000"
 #   network_mode: host
volumes:
  grafana_data: { }
  prometheus_data: { }
