version: "3.7"
services:
   #服务名称
  mysql:
   #容器名称
   container_name: mysql
   #镜像名称
   image: mysql
   #自动启动
   restart: always
   #端口映射
   ports:
     - "3306:3306"
   #环境变量
   environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_PASS=root
   #挂载
   volumes:
     - ./conf:/etc/mysql/conf.d
     - ./logs:/logs
     - ./data:/var/lib/mysql
     
  phpmyadmin:  #这里本人还配置了phpmyadmin容器，相当于连接mysql的客户端工具
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always        
      ports:
       - 3300:80  #宿主机和容器间的端口映射，可自行配置
      environment:
        PMA_ARBITRARY: 1
        TZ: Asia/Shanghai
        UPLOAD_LIMIT: 100M 

