// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cloudwego/kitex/pkg/klog"
	"github.com/cloudwego/kitex/server"
	"greet/internel/biz"
	"greet/internel/conf"
	"greet/internel/data"
	server2 "greet/internel/server"
	"greet/internel/service"
)

// Injectors from wire.go:

//*polaris.Registry, *registry.Info
func initApp(ctxLogger klog.CtxLogger, config *conf.Config) (server.Server, func(), error) {
	clientSuite := service.NewDiscover(config, ctxLogger)
	client := service.NewHelloClient(config, clientSuite, ctxLogger)
	dataData, cleanup, err := data.NewData(ctxLogger, client)
	if err != nil {
		return nil, nil, err
	}
	greetRepo := data.NewGreetRepo(dataData)
	greetUseCase := biz.NewGreetUseCase(greetRepo, ctxLogger)
	greetService := service.NewGreetService(greetUseCase, ctxLogger)
	serverServer := server2.NewRPCServer(greetService, config, ctxLogger)
	return serverServer, func() {
		cleanup()
	}, nil
}
