// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cloudwego/kitex/pkg/klog"
	"github.com/cloudwego/kitex/server"
	"hello/internal/biz"
	"hello/internal/conf"
	"hello/internal/data"
	server2 "hello/internal/server"
	"hello/internal/service"
)

// Injectors from wire.go:

//*polaris.Registry, *registry.Info
func initApp(ctxLogger klog.CtxLogger, config *conf.Config) (server.Server, func(), error) {
	client := data.NewDBClient(ctxLogger, config)
	redisClient := data.NewRedisClient(ctxLogger, config)
	dataData, cleanup, err := data.NewData(ctxLogger, client, redisClient)
	if err != nil {
		return nil, nil, err
	}
	helloRepo := data.NewHelloRepo(dataData)
	helloUseCase := biz.NewHelloUseCase(helloRepo, ctxLogger)
	helloService := service.NewHelloService(helloUseCase, ctxLogger)
	serverServer := server2.NewRPCServer(helloService, config, ctxLogger)
	return serverServer, func() {
		cleanup()
	}, nil
}
