// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"examples/app/hello/internel/biz"
	"examples/app/hello/internel/conf"
	"examples/app/hello/internel/data"
	server2 "examples/app/hello/internel/server"
	"examples/app/hello/internel/service"
	"github.com/cloudwego/kitex/pkg/klog"
	"github.com/cloudwego/kitex/server"
)

// Injectors from wire.go:

//*polaris.Registry, *registry.Info
func initApp(ctxLogger klog.CtxLogger, config *conf.Config) (server.Server, func(), error) {
	dataData, cleanup, err := data.NewData(ctxLogger)
	if err != nil {
		return nil, nil, err
	}
	helloRepo := data.NewHelloRepo(dataData)
	helloUseCase := biz.NewHelloUseCase(helloRepo, ctxLogger)
	helloService := service.NewHelloService(helloUseCase, ctxLogger)
	serverServer := server2.NewRPCServer(helloService, config, ctxLogger)
	return serverServer, func() {
		cleanup()
	}, nil
}
