// Code generated by Kitex v0.4.3. DO NOT EDIT.
package xxx

import (
	server "github.com/cloudwego/kitex/server"
	v1 "xxx/kitex_gen/xxx/v1"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler v1.XXX, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
